### ISSUE TITLE
Webui prompt validator highlights NPW as error

### ISSUE THREAD

**Issue by jordanjay29** [muerrilla/stable-diffusion-NPW#3]
I was noticing the prompt validator (which highlights the prompt token counts in red when there's an error) was going off whenever NPW is active (set to a non-1 value). It's not throwing an error or making trouble, so this probably isn't a huge priority. It simply took me a few weeks to diagnose because there was no tooltip to guide me and I didn't think it had anything to do with NPW. 

Not sure if this can be fixed on your end, or is a webui (A1111/Vlad) thing. Just wanted to bring it up so you'd be aware. Maybe a friendlier message/tooltip is possible, or NPW can be exempted from the validator's error checking.

**Comment by muerrilla** [comment]
It's not an error. I put the red border around the token counter as a visual feedback, so you don't leave the NPW slider on a non-1 value and forget about it (there's also a message printed to console). Had no idea the token counter already turned red when there are errors in the prompt, and that it can thus cause more confusion. 

Tooltips are not possible (because of the way it's done), so best I could do was point to it in the [readme](https://github.com/muerrilla/stable-diffusion-NPW#usage). Any suggestions on what to do with it?

**Comment by jordanjay29** [comment]
Not sure. I'm guessing you have no control over the highlight color? If so, could change it to yellow to be different enough (and yellow is traditionally more of a warning than error alert color).

In which case the only suggestion I'd have to do more is talk with Automatic or Vladmandic about more control from the extension side, so you can pass a tooltip alongside. Tooltips exist for the prompt when it detects wrong numbers of square/round brackets, for example, having one that explains 'NPW is enabled' would help diffuse confusion about the reminder you're setting.

**Comment by muerrilla** [comment]
I changed the color to yellow and moved it to npw's own x button instead of the token counter. Should be self-explanatory that way.
