### ISSUE TITLE
The slider didn't automatically update.

### ISSUE THREAD

**Issue by songib** [muerrilla/stable-diffusion-NPW#5]
or is it worked that way since the beginning?
so I just type the number most of the time, it will be more convenient if the slider updates when we use it, and maybe at 0.05 increment.

**Comment by muerrilla** [comment]
Sorry, haven't had time to update my webui to the latest version in a while, so not sure what's going on. The slider is supposed to update the number when released (instead of when slid) because of a problem in the older Gradio versions. I'll fix it as soon as I update my webui.

In the mean time you can edit `npw.py` at line 39 and change `weight_input_slider.release` to `weight_input_slider.change`, and at line 22 change `step` to .05 too.

**Comment by songib** [comment]
ah, so it's gradio problem i see. 
For now, it seems like it's more broken since the slider didn't even update after I use it, so just typed the number for now.

**Comment by muerrilla** [comment]
It's all working fine over here. Which Gradio version are you on (it's written at the bottom of the webui, just in case)?
